#spring.data.mongodb.host = localhost
#spring.data.mongodb.port = 27017
spring.data.mongodb.uri = mongodb+srv://sonalichaudhari219:TLobi3PoeUFDSDkx@cluster0.smpyd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database = journaldb
spring.data.mongodb.auto-index-creation = true
#spring.data.mongodb.username = ---
#spring.data.mongodb.password = ---
#spring.redis.uri = redis://default:I0taR02RUoU7Xqeb48BsHY1WtwFHsweX@redis-10989.crce179.ap-south-1-1.ec2.redns.redis-cloud.com
spring.redis.host = redis-10989.crce179.ap-south-1-1.ec2.redns.redis-cloud.com
spring.redis.port = 10989
spring.redis.passowrd = Sonali219@
server.servlet.context-path=/journalApp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sonalichaudhari219@gmail.com
spring.mail.password=xtsx bqof vdgd lxdx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.ssl.enable=true
